export default {
    CURRENCIES_REQUEST: 'CURRENCIES_REQUEST',
    CURRENCIES_SET: 'CURRENCIES_SET',
    INITIAL_CURRENCY_SET: 'INITIAL_CURRENCY_SET',
    TARGET_CURRENCY_SET: 'TARGET_CURRENCY_SET',
};