export default {
    CURRENCIES_REQUEST: 'CURRENCIES_REQUEST',
    CURRENCIES_SET: 'CURRENCIES_SET',
    CONVERT_CURRENCIES_SET: 'CONVERT_CURRENCIES_SET',
    CONVERT_RATE_SET: 'CONVERT_RATE_SET',
    CONVERT_RATE_POLLING_START: 'CONVERT_RATE_POLLING_START',
    CONVERT_RATE_POLLING_END: 'CONVERT_RATE_POLLING_END',
    CONVERT_AMOUNT_SET: 'CONVERT_AMOUNT_SET',
    CONVERTATION_REQUEST: 'CONVERTATION_REQUEST',
    CONVERTED_CURRENCIES_SET: 'CONVERTED_CURRENCIES_SET',
};