export default {
    CURRENCIES_REQUEST: 'CURRENCIES_REQUEST',
    CURRENCIES_SET: 'CURRENCIES_SET',
    CONVERT_CURRENCIES_SET: 'CONVERT_CURRENCIES_SET',
    CONVERT_RATE_SET: 'CONVERT_RATE_SET',
    CONVERT_RATE_POLLING_START: 'CONVERT_RATE_POLLING_START',
    CONVERT_RATE_POLLING_END: 'CONVERT_RATE_POLLING_END',
};